AM_CPPFLAGS = -I$(top_srcdir)/include -I$(srcdir)/../

noinst_LIBRARIES = libsoa_rewrite_vgame_en.a

libsoa_rewrite_vgame_en_a_SOURCES = \
		soa_seg000.cpp soa_seg000.h\
		soa_seg001.cpp soa_seg001.h\
		soa_seg002.cpp soa_seg002.h\
		soa_seg003.cpp soa_seg003.h\
		soa_seg004.cpp soa_seg004.h\
		soa_seg005.cpp soa_seg005.h\
		soa_seg006.cpp soa_seg006.h\
		soa_seg007.cpp soa_seg007.h\
		soa_seg008.cpp soa_seg008.h\
		soa_seg009.cpp soa_seg009.h\
		soa_seg010.cpp soa_seg010.h\
		soa_seg011.cpp soa_seg011.h\
		soa_seg012.cpp soa_seg012.h
