RealPt FIG_get_ptr(char v1);
void FIG_set_gfx();
void FIG_draw_pic();
RealPt FIG_get_hero_ptr(unsigned short v1);
RealPt seg006_033c(short v);
void FIG_set_0e(char id, char val);
void FIG_reset_12_13(char id);
void FIG_set_12_13(char id);
void FIG_set_0f(char id, char va);
void FIG_remove_from_list(char id, char v2);
void FIG_draw_char_pic(unsigned short pos, unsigned short hero_nr);
void FIG_draw_enemy_pic(unsigned short pos, unsigned short enemy_nr);
